export const regYears = ["2000 - 2010", "2010 - 2015", "2015 - 2020", "All"];
export const kmsDriven = [
  "Brand New",
  "0 - 5000",
  "5000 - 10000",
  "10000 - 15000",
  "15000 - 20000",
  "20000 & Above",
];
export const budget = [
  "Less Than 50L",
  "50L to 1Cr",
  "1Cr to 1.5Cr",
  "1.5Cr & Above",
];
export const bodyTypes = [
  "SUV",
  "Sedan",
  "Convertible",
  "Coupe",
  "Sports",
  "MUV-MPV",
  "Hatchback",
  "Bike",
];
export const brands = [
  "Select Brand",
  "Aprilia",
  "Aston Martin",
  "Audi",
  "Avanturaa Choppers",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "DC",
  "Ducati",
  "Ferrari",
  "Fiat",
  "Ford",
  "Harley Davidson",
  "Honda",
  "Hummer",
  "Hyundai",
  "Indian",
  "Infinity",
  "Jaguar",
  "Jeep",
  "Kawasaki",
  "KIA",
  "KTM",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Maserati",
  "Maybach",
  "McLaren",
  "Mercedes-Benz",
  "Mini",
  "MV Agusta",
  "Nissan",
  "Porsche",
  "Rolls-Royce",
  "Royal Enfield",
  "Skoda",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Triumph",
  "Volkswagen",
  "Volvo"
];